apiVersion: apps/v1
kind: Deployment
metadata:
  name: webchat-okteto-backend
spec:
  selector:
    matchLabels:
      app: webchat-okteto-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: webchat-okteto-backend
    spec:
      containers:
      - name: webchat-okteto-backend
        image: pedroantonacio/webchat-okteto-backend:latest
        ports:
        - containerPort: 443