apiVersion: apps/v1
kind: Deployment
metadata:
  name: webchat-okteto-frontend
spec:
  selector:
    matchLabels:
      app: webchat-okteto-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: webchat-okteto-frontend
    spec:
      containers:
      - name: webchat-okteto-frontend
        image: pedroantonacio/webchat-okteto-frontend:latest
        ports:
        - containerPort: 3000